---
# Include at the start of each resource creation playbook
- name: Validate controller credentials
  ansible.builtin.assert:
    that:
      - aap_host is defined
      - aap_username is defined
      - aap_password is defined
    fail_msg: "Missing credentials. Configure vars/local.yml"
