---
- name: Create AAP host
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/aap_defaults.yml
  tasks:
    - ansible.builtin.import_tasks: tasks/validate_connection.yml

    - name: Create or update host
      ansible.controller.host:
        name: "{{ host_name }}"
        inventory: "{{ inventory }}"
        description: "{{ description | default('') }}"
        enabled: "{{ enabled | default(true) }}"
        variables: "{{ variables | default(omit) }}"
        state: present
        controller_host: "{{ controller_connection.controller_host }}"
        controller_username: "{{ controller_connection.controller_username }}"
        controller_password: "{{ controller_connection.controller_password }}"
        validate_certs: "{{ controller_connection.validate_certs }}"
      vars:
        host_name: "{{ host_name | mandatory }}"
        inventory: "{{ inventory | mandatory }}"

    - ansible.builtin.debug:
        msg: "Host '{{ host_name }}' no inventory '{{ inventory }}'"
