---
- name: Create AAP label
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/aap_defaults.yml
  tasks:
    - ansible.builtin.import_tasks: tasks/validate_connection.yml

    - name: Create or update label
      ansible.controller.label:
        name: "{{ label_name }}"
        organization: "{{ organization | default(aap_organization_default) }}"
        state: present
        controller_host: "{{ controller_connection.controller_host }}"
        controller_username: "{{ controller_connection.controller_username }}"
        controller_password: "{{ controller_connection.controller_password }}"
        validate_certs: "{{ controller_connection.validate_certs }}"
      vars:
        label_name: "{{ label_name | mandatory }}"

    - ansible.builtin.debug:
        msg: "Label '{{ label_name }}' in '{{ organization | default(aap_organization_default) }}'"
